### ISSUE TITLE
Write a contribution guide

### ISSUE THREAD

**Issue by dykeaura** [gaylor-wiki/gaylor-vault#2]
This is supposed to be a community wiki, which means other people have to help. They can't do that if they don't know how! This guide should be as thorough as possible, explaining things in very precise detail. We need to reduce the barrier of entry a lot.

I will look for any git guides that may already be out there, that would be a good starting point at least.
I also want to let them know that if after all this they still don't get it, they can just message me (on any platform, really) about anything they want to add or change and I'll figure it out. It's a lot for people.

The main page should really just link out to the 3 main areas, otherwise it would get massive. But it should do it in the way that is most intuitive to consume - someone probably isn't going there to read through the whole thing in one go like a book. They clicked on it because they wanted help learning to do something specific, like submit a suggestion or write a note of their own. Reading the whole thing at once would just be overwhelming them with information and leave them less likely to actually end up contributing anything at all.

We need to explain:
- [x] git
    - [x] overview/diffs
    - [x] commits
         - [x] staging
    - [x] remotes
    - [x] push/pull
    - [x] branches
    - [x] merges
        - [x] merge conflicts
        - [x] merge types
- [x] github
    - [x] issues
    - [x] forks
    - [x] pull requests
- [x] obsidian (direct them to the help vault)
    - [x] quick-start guide
    - [x] view modes
        - stay in reading mode as much as possible to avoid unwanted changes
    - [x] plugins we use
        - discretion about installing new ones

**Comment by dykeaura** [comment]
thank god i'm finally done
